version: "3"
services:
  mysql:
    image: mysql:latest
    working_dir: /code
    container_name: mysql_ins
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql:rw #创建 /data/myql 目录
      - ./mysql/logs:/var/lib/mysql-logs:rw  # /logs/mysql 目录
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: 123456 
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - net-mysql
  php:
    build: ./php
    container_name: php_ins
    ports:
      - "9000:9000"
    working_dir: /code
    volumes:
      - ./code:/code
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - net-php
      - net-mysql
      - net-redis
  redis:
    working_dir: /code
    image: redis:latest
    container_name: redis_ins
    ports:
      - "6379:6379"
    networks:
      - net-redis
  nginx:
    image: nginx:latest
    container_name: nginx_ins
    working_dir: /code
    ports:
      - "80:80"
    volumes:
      - ./code:/code  #创建项目根目录，根据自己的情况来定
      - ./nginx/conf.d:/etc/nginx/conf.d  #可以把ngixn配置映射出来，便于修改
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - net-php

networks:
  net-php:
  net-mysql:
  net-redis: